"""
Django settings for gymbackend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
import os
from dotenv import load_dotenv

# =============================================================================
# ENVIRONMENT CONFIGURATION
# =============================================================================
# Load environment variables from .env file
# This keeps sensitive credentials out of source code
# =============================================================================

load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set DJANGO_SECRET_KEY in .env file
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-o5g(3u*&zwgqyc335bhjismlvu*w)6tjqor%0rd7eca-wuyqn1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Allowed hosts - add your production domain here
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'members',
    'notifications',
    'django_crontab',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gymbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gymbackend.wsgi.application'


# =============================================================================
# DATABASE CONFIGURATION - SUPABASE POSTGRESQL
# =============================================================================
# Configured to connect to Supabase cloud PostgreSQL
# SSL is required for secure cloud connections
#
# Environment variables (from .env):
#   DB_NAME     - Database name (default: postgres for Supabase)
#   DB_USER     - Database user
#   DB_PASSWORD - Database password
#   DB_HOST     - Supabase host (db.xxx.supabase.co)
#   DB_PORT     - PostgreSQL port (default: 5432)
#   DB_SSL_MODE - SSL mode (require for Supabase)
# =============================================================================

# Get SSL mode from environment (default: require for Supabase)
DB_SSL_MODE = os.getenv('DB_SSL_MODE', 'require')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # SSL Options for Supabase connection
        # sslmode=require ensures encrypted connection to cloud database
        'OPTIONS': {
            'sslmode': DB_SSL_MODE,
        } if DB_SSL_MODE != 'disable' else {},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# django-crontab jobs (to be filled in notifications app)
# django-crontab jobs (to be filled in notifications app)
CRONJOBS = [
    ('0 7 * * *', 'notifications.cron.send_membership_reminders'),  # Every day at 7am
]

# CORS settings for React frontend
# Add your Netlify URL to CORS_ALLOWED_ORIGINS environment variable
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://localhost:3001'
).split(',')

# Allow credentials (cookies) for CORS requests
CORS_ALLOW_CREDENTIALS = True


# =============================================================================
# NOTIFICATION SYSTEM CONFIGURATION
# =============================================================================
# Provider-agnostic notification system
# Currently uses mock provider (logs to console)
# Can be switched to real SMS providers (MSG91, Twilio) later
#
# To switch to real SMS:
# 1. Set NOTIFICATION_PROVIDER=msg91 or twilio in .env
# 2. Add provider credentials (MSG91_API_KEY, etc.)
# 3. Implement provider class in notifications/providers/
# =============================================================================

# Notification provider: 'mock' (default), 'msg91', 'twilio'
NOTIFICATION_PROVIDER = os.getenv('NOTIFICATION_PROVIDER', 'mock')

# Gym name used in notification messages
GYM_NAME = os.getenv('GYM_NAME', 'FitZone Gym')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
